### ISSUE TITLE
JAR has no manifest and can't be executed

### ISSUE THREAD

**Issue by karianna** [spoofzu/DeepViolet#19]
`mvn clean install` from HEAD followed by `cd target` then `java -jar DeepViolet-0.0.1-SNAPSHOT-jar-with-dependencies.jar` reports:

`no main manifest attribute, in DeepViolet-0.0.1-SNAPSHOT-jar-with-dependencies.jar`

**Comment by spoofzu** [comment]
Appreciate you taking the time to give this a try Martijn.  If you do a mvn clean install and the build is successful then you should notice a few other jars in the same directory: dvAPI.jar, dvCMD.jar, and dvUI.jar.  The jars are specified within the pom.xml, they are the project binary executables, and their purpose is as follows: dvAPI.jar = include this in your projects to extend TLS/SSL scanning support, dvCMD.jar = This jar supports the command line reference case for DeepViolet.  The output of this jar can combined with other programs and used in shell scripts and used in so many useful ways.  dvUI.jar = This jar supports the desktop application reference case for DeepViolet.  The dvUI.jar includes DeepViolet features and in a Swing based desktop application.  If you see these files and you double-click on the dvUI.jar from your desktop, the user interface will be presented.  Type in a URL to be scanned and you will begin to see results.  I tried a mvn clean install on my system, my build was successful, and these jars were produced.  I'm assuming you didn't realize the purpose of the dv*.jar files.  I would appreciate if you let me know if your successful or continue to have troubles.  If you continue to have troubles I will clone a new project and investigate more thoroughly.  Thanks again!

**Comment by javabeanz** [comment]
I just built deepviolet on my laptop, but the dv*.jars are not created.

**Comment by karianna** [comment]
Hi @spoofzu and @javabeanz - I have the same issue.

Mac Os X 10.12.1, JDK 1.8_112, Maven 3.3.9

Maven build with -X attached.

[build.txt](https://github.com/spoofzu/DeepViolet/files/558124/build.txt)

**Comment by javabeanz** [comment]
tag 1.1.000 still did have the dv*.jars. at tag 1.2.000 they are gone. Note that they seem not generated but prebuilt.

**Comment by spoofzu** [comment]
Ok, I have it figured out.  I have some code I "assumed" I delivered but did not.  Hat tip to @karianna.  Apologize for making you my beta tester but I'm happy you identified the issue.  I will get this fixed up and deliver but it might take me a couple of days.  I am working through my backlog, over the weekend (ouch).  ;o)  I will update this thread when delivered to proactively notify you both.  Thanks!

**Comment by spoofzu** [comment]
Should work now, thanks again.

**Comment by javabeanz** [comment]
fix confirmed.

**Comment by fatihersinadim** [comment]
Hi @spoofzu I still have the same issue.

I built DeepViolet with "mvn clean install", but the dv*.jars are not created.

```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T18:41:47+02:00)
Java version: 1.8.0_73, vendor: Oracle Corporation
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.3", arch: "x86_64", family: "mac"
```
